import { Inter } from "next/font/google";
import './globals.css'
import './responsive.css'
import "bootstrap/dist/css/bootstrap.min.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import ThemeProvider from "@/context/ThemeProvider";
import Header from "@/component/header/header";
import Footer from "@/component/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <div id="root"> */}
          <ThemeProvider>
            <Header />
            {children}
            <Footer />
          </ThemeProvider>
        {/* </div> */}
      </body>
    </html>
  );
}
